### ISSUE TITLE
scenarios.py fails with KeyError: 'pct_sample_if_to_detection'

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/popsborder#118]
The scenarios.py script fails likely due to outdated configuration.

Error:

```
Traceback (most recent call last):
  File "scenarios.py", line 59, in <module>
    main()
  File "scenarios.py", line 19, in main
    save_scenario_result_to_table(
  File "/home/vpetras/Projects/pathways/pathways-simulation/pathways/outputs.py", line 576, in save_scenario_result_to_table
    row[column] = get_item_from_nested_dict(result.__dict__, keys)
  File "/home/vpetras/Projects/pathways/pathways-simulation/pathways/outputs.py", line 547, in get_item_from_nested_dict
    return reduce(operator.getitem, keys, dictionary)
KeyError: 'pct_sample_if_to_detection'
```

To reproduce, run:

```
python scenarios.py
```

**Comment by wenzeslaus** [comment]
Example script updated to new variable name and script is now running in the CI, so it should not happen again.
